### ISSUE TITLE
[Question] Does it support passing name as prop?

### ISSUE THREAD

**Issue by Whoaa512** [yesmeck/redux-modal#2]
Such that I can pass the `name` at design time OR at runtime via a prop? Similar to how redux-form works (http://redux-form.com/4.2.0/#/api/reduxForm)

**Comment by yesmeck** [comment]
Do you mean dynamic modal like [dynamic form](http://redux-form.com/4.2.0/#/examples/dynamic?_k=5iyb5v)?

**Comment by Whoaa512** [comment]
No I mean can I pass the modal name as a prop to the component instead of declaring it when I connect it with `redux-modal`. Similar to how I can pass the `form` prop to a component that was connected with `redux-form`.

**Comment by yesmeck** [comment]
@Whoaa512 Could you please provide a redux-form example?

**Comment by yesmeck** [comment]
Do you mean this:

```javascript
class App extends Component {
  render() {
    const WrappedMyModal = connectModal({ name: this.props.name})(MyModal)

    return (
      <div>
        <WrappedMyModal />
      </div>
    )
  }
}
```

**Comment by Whoaa512** [comment]
Close but I want to be able to export the connected component without declaring the `name` until I use the connected version like so:

```javascript
// MyModal.js
class MyModal extends Component {
  render() {
    return (
      <div>Hello</div>
    )
  }
}

export default connectModal()(MyModal)
```

```javascript
// App.js
import WrappedMyModal from './MyModal'

class App extends Component {
  render() {
    return (
      <div>
        <WrappedMyModal name={'simpleModal'}/>
      </div>
    )
  }
}
```

**Comment by yesmeck** [comment]
Yes, you can create a higher order component for your modal. Look at the commit above.

**Comment by yesmeck** [comment]
Updated the example https://github.com/yesmeck/redux-modal/blob/master/example/src/containers/HOCModal.js

**Comment by Whoaa512** [comment]
This will work.
