### ISSUE TITLE
Reducer return immutable object

### ISSUE THREAD

**Issue by hoetmaaiers** [yesmeck/redux-modal#3]
The reducer turns props provided to `dispatch(show('modal-name', props))` into immutable properties. This is a problem when doing for example .map on an Array property.

As a quick fix I added `.asMutable()` when returning the new state after reducing. Could something alike be a final fix?

**Comment by yesmeck** [comment]
@hoetmaaiers I have removed seamless-immutable dependency, and release a new [version](https://github.com/yesmeck/redux-modal/releases/tag/v1.2.6).

**Comment by hoetmaaiers** [comment]
Thank you! Just tested and it works fine.
