### ISSUE TITLE
"destroy" action creator is not mentioned in the API docs

### ISSUE THREAD

**Issue by dpikt** [yesmeck/redux-modal#35]
When and how should it be used?

**Comment by yesmeck** [comment]
It's not a public API, you don't need call this action manually.

**Comment by yesmeck** [comment]
When you set `destroyOnHide` to `true`, modal will been destroyed after you called `handleHide`.

**Comment by yesmeck** [comment]
Oh...Sorry, I forgot it is documented https://github.com/yesmeck/redux-modal/blob/master/docs/api.md#examples 

See https://github.com/yesmeck/redux-modal/pull/11

**Comment by dpikt** [comment]
@yesmeck I see. I was confused because that action creator is still being exported from the library. Is that to maintain backwards compatibility?

**Comment by yesmeck** [comment]
@dpikt My mistake, it's useful, see #11.
