### ISSUE TITLE
Weird bug between redux-modal and redux-form

### ISSUE THREAD

**Issue by zomars** [yesmeck/redux-modal#42]
I'm using redux-modal to show when the user is submitting a form, and for some reason, every time redux-form dispatches an action is followed by a "@redux-modal/DESTROY" action.

**Comment by zomars** [comment]
I've made a test case, if you try to do anything with the form, the modal is destroyed.

https://codesandbox.io/s/w53o747o7

**Comment by yesmeck** [comment]
> every time redux-form dispatches an action is followed by a "" action.

Can not reproduce in your codesandbox link.

**Comment by zomars** [comment]
Also i forgot to mention that The action dispatched is the "destroy" action

**Comment by zomars** [comment]
Sorry for bothering, I've made some changes to the test case so it can be reproducible. When you click the button that submits and opens the modal, the "redux-modal/DESTROY" action is being called and I can't understand why.  Here's it in action:

![it-working1](https://user-images.githubusercontent.com/3504472/39009772-cd986ab0-43c9-11e8-814b-b0964a1a8db8.gif)

Only when you click for the second time, the modals shows up.

**Comment by yesmeck** [comment]
I've made a mistake in the demo, you just can't create component in `render` function, I've removed the `DynamicModal` from the demo.

**Comment by zomars** [comment]
Thanks for the response! I've fixed it by turning into a High Order Component:

```js
const withModal = PassedComponent => ({ children, name, ...props }) => {
  PassedComponent = connectModal({
    name,
    destroyOnHide: false
  })(PassedComponent)

  return <PassedComponent children={children} {...props} />
}

export default withModal(Modal)
```
