### ISSUE TITLE
No reducer provided for key "modal"

### ISSUE THREAD

**Issue by PredokMiF** [yesmeck/redux-modal#46]
Unable to build project after update to v2.
From browser js console: **No reducer provided for key "modal"**. It is related to [bug](https://github.com/yesmeck/redux-modal/issues/45)

``` JS
// This is not working
import { reducer as modal } from 'redux-modal';

// This works fine
import reduxModal from 'redux-modal';
const modal = reduxModal.reducer;
```

This bekause module exports default, which contains other fields - it is wrong, I think. You can use [doc link](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/export):
```js
export * from ...
```

**Comment by yesmeck** [comment]
Fixed in 2.0.2, thanks for reporting.
