### ISSUE TITLE
How to update processed props passed to modal (to cause component to rerender)?

### ISSUE THREAD

**Issue by nbkhope** [yesmeck/redux-modal#57]
Say you do
```
this.props.show('myModal', { myProp: this.processData() });
```

From inside the modal, I call a method that updates data from the component that called the above. Because the prop is not directly passed to the modal, but a processed value first, the modal will not be rerendered. How would you guys handle this case?

**Comment by nbkhope** [comment]
https://codesandbox.io/s/pwwx63xv07

1) Note data has inactive flag
2) Click to open modal
3) Click to update parent data
4) Data in modal is unchanged because it only receives it as prop once
5) Close modal and verify parent data is updated
6) Open modal again, data will have been updated

Just wondering how you'd update the data that was passed from the parent, because it's not simply linking to the parent prop, but the data needs to go through some processing first before being given to the modal.

**Comment by yesmeck** [comment]
You should pass data as modal's props:

```javascript
<MyModal someData={this.state.someData} />
```

**Comment by nbkhope** [comment]
What if you can't do that?
