### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by petrgazarov** [yesmeck/redux-modal#72]
I'm copying from the Readme with a simple usage:

```
import React from 'react';

class MyModal extends React.Component {
  render() {
    return(
      //...
    )
  }
}

export default connectModal({ name: 'myModal' })(MyModal);
```

But the component does not show up. The render() method of MyModal never gets called.

I'm able to successfully render the component by just changing the export line:
```
export default MyModal;
```

I'm using:
```
redux-modal@2.0.3
react@16.5.0
react-redux@5.0.7
react-dom@16.5.0
```

**Comment by yesmeck** [comment]
Could you reproduce your issue on https://codesandebox.io?

**Comment by ismaildervisoglu** [comment]
@yesmeck @petrgazarov  I am using react-redux and I have the same problem. What is the solution?
