### ISSUE TITLE
DESTROY doesn't clean up state completely

### ISSUE THREAD

**Issue by Persi** [yesmeck/redux-modal#74]
Destroying a modal causes the key of the modal to be undefined in state. While iterating over the entries of that state with Object.entries, you have to explicitely filter for undefined values.

That is uncomfortable and erroneous, as you have to do it every time you have to iterate.

Is there a reason to keep the keys in state without a reference to a modal, instead of deleting the key completely with "delete"?

**Comment by yesmeck** [comment]
Try 2.0.4

**Comment by Persi** [comment]
Thx @yesmeck for the fast reaction and fix!
