### ISSUE TITLE
Need to add delay before modal removed

### ISSUE THREAD

**Issue by anatoliykot** [yesmeck/redux-modal#8]
I can't use animations because modals unmount immediately by `handleHide` and I can't use `destroyOnHide: false` because I'll not have `componentDidMount` calls to fetch some data.

My workaround:
```
destroyModalAfterHideWithDelay = () => {
    const delayed = () => _.delay(this.props.destroy, 300, modalName);
    this.props.handleHide()
    delayed()
}
```
Suggestion:
```
if (!modal.show) {
    return destroyOnHide ? _.delay(this.props.destroy, this.props.delay, name) : this.hide()
}
```
I'm not sure about naming `delay`, maybe `delayOnHide`

**Comment by yesmeck** [comment]
How about `destroyOnHide` can be a `number`, if a `number`, let's say `3000` pass to `destroyOnHide`, then modal will be destroyed after 3 seconds later.

**Comment by anatoliykot** [comment]
yeah, I think it's fine too

**Comment by yesmeck** [comment]
@anatoliykot Which model component are you using?

**Comment by anatoliykot** [comment]
@yesmeck BootstrapModal

**Comment by anatoliykot** [comment]
@yesmeck any updates?

**Comment by yesmeck** [comment]
Hello @anatoliykot , now you can use `handleDestroy` to destroy modal by yourself.
