### ISSUE TITLE
Need to add support for new Context API

### ISSUE THREAD

**Issue by viktor-equinix** [yesmeck/redux-modal#91]
react-redux@6 moved to new Context API and now  using redux-modal we have warning about missing store in context.

**Comment by yesmeck** [comment]
@viktor-equinix Could you open a PR?

**Comment by matthewlilley** [comment]
@viktor-equinix Leaving this here for reference. If I get a chance, I'll make a PR.

https://github.com/reduxjs/react-redux/releases/tag/v6.0.0

**Comment by cozmy** [comment]
> @viktor-equinix Could you open a PR?

I could. The changes are very minimal. But somehow, I'm breaking your TS build :(
Besides the update to react-redux v6, this is all that's needed:

![image](https://user-images.githubusercontent.com/5887290/50340141-1f10e400-051a-11e9-9334-b278af658055.png)

**Comment by yesmeck** [comment]
@cozmy We need a major version release.

**Comment by yesmeck** [comment]
Released https://github.com/yesmeck/redux-modal/releases/tag/3.0.0
