### ISSUE TITLE
Lifecycle method componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by nbkhope** [yesmeck/redux-modal#95]
Will there be any updates to the package so that it no longer uses the deprecated lifecycle method `componentWillReceiveProps`?

Ref https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

connectModal, for example, uses it:
https://github.com/yesmeck/redux-modal/blob/3bacc1280cfd568b20c9284fde23f3af0889b502/src/connectModal.ts#L39

**Comment by veeramarni** [comment]
@yesmeck Do you need PR to replace `componentWillReceiveProps` with `componentDidUpdate`?

**Comment by yesmeck** [comment]
@veeramarni Yes

**Comment by codeskills-nl** [comment]
Just run: npx react-codemod rename-unsafe-lifecycles (or rename manually componentWillReceiveProps to UNSAFE_ componentWillReceiveProps)
It will suppress the warning

**Comment by codeskills-nl** [comment]
Replace componentWillReceiveProps with:

      componentDidUpdate() {
        const { modal } = this.props;

        if (isUndefined(modal.show)) {
          return this.unmount();
        }

        if (!modal.show) {
          return destroyOnHide ? this.props.destroy(name) : this.hide();
        }

        if (!resolve) {
          this.show();
        }

        if (resolve) {
          const resolveResult = resolve({ props: modal.props });
          if (!isPromise(resolveResult)) {
            return this.show();
          }
          resolveResult.then(() => {
            this.show();
          });
        }
      }

**Comment by masaokiba** [comment]
@yesmeck are you fixing this deprecation issue?

**Comment by dchavours** [comment]
I am interested in this issue as well.

**Comment by yesmeck** [comment]
PRs are welcome

**Comment by leo-esaki** [comment]
@yesmeck I wanna create a PR but I don't have a permission?

**Comment by yesmeck** [comment]
@leo-esaki  You need to [fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) this repo before [create a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by yesmeck** [comment]
Released 4.0.0
