### ISSUE TITLE
Is there a best practice to code split with a connected modal?

### ISSUE THREAD

**Issue by nbkhope** [yesmeck/redux-modal#96]
I have an application that has many connected modals at the top-level component.

The problem is the app doesn't need to load all of their code for a first time user experience.

So I want to code-split the modals so they are only loaded as needed.

Is there a best practice you would suggest?

If I attempt to dynamically load the connected modal itself, it won't work because at the top-level component, all modals are included and that by itself will trigger a fetch to get all the code chunks for each modal.

I could return a component decorated with connectModal, but would have to move the modal logic to another component and make it a lazy component. That would introduce a layer of wrapping:
```
const MyModalWrapper = React.lazy(() => import('./MyActualModal'))

connectModal({ ... })(MyModalWrapper)
```

I'd like to know if there's a better way to handle this.

**Comment by yesmeck** [comment]
You should call `connectModal` inside `./MyActualModal`.
