### ISSUE TITLE
How to access action types

### ISSUE THREAD

**Issue by Kif11** [yesmeck/redux-modal#98]
I'm trying to import action types to my reducer from `lib/actionTypes.js` but it is not included in `index.js` of this module. Do I miss something?

**Comment by yesmeck** [comment]
Why do you need action types?

**Comment by Kif11** [comment]
Because I need to update some of the reduces on modal DESTROY.

**Comment by yesmeck** [comment]
How about dispatch your action after destroy modal? The actions for `redux-modal` are not supposed to export.

```javascript
modal.destroy();
dispatch({
  type: 'your/action',
})
```
