### ISSUE TITLE
react-redux@7 support

### ISSUE THREAD

**Issue by dpikt** [yesmeck/redux-modal#99]
Right now, react-redux@7 is not in the peer dependency range. Is support for this on the roadmap?

**Comment by skwon-mdsol** [comment]
Bumping on this. Is there a way we can make this compatible with react-redux 7 so we can use hooks?

**Comment by skwon-mdsol** [comment]
```
    "react": "^0.14.0 || >=15.0.0",
    "react-redux": "^4.0.0 || ^5.0.0 || ^6.0.0",
    "redux": "^3.0.0 || ^4.0.0"
```

The difficulty is that this repo is already supporting very low versions of react which may lead to a breaking change for those using lower versions of react.

**Comment by skwon-mdsol** [comment]
https://github.com/yesmeck/redux-modal/pulls i think we can close this now. @dpikt

**Comment by dpikt** [comment]
👀 that was quick. Thanks!
